apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: feast-online-model
  namespace: feast-demo
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    model:
      modelFormat:
        name: feast-numpy
        version: "1"
      protocolVersion: v2
      runtime: feast-numpy-runtime
      storageUri: pvc://feast-notebook-model
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: "1"
          memory: 1Gi
