apiVersion: v1
kind: ServiceAccount
metadata:
  name: feast-spark
  namespace: feast-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: feast-spark
  namespace: feast-demo
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: feast-spark
  namespace: feast-demo
subjects:
  - kind: ServiceAccount
    name: feast-spark
    namespace: feast-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: feast-spark
