title: Alauda AI
logoText: Alauda AI
lang: en
api:
  crds:
    - docs/shared/crds/*.yaml
  openapis:
    - docs/shared/openapis/*.json
permission:
  functionresources:
    - docs/shared/functionresources/*.yaml
  roletemplates:
    - docs/shared/roletemplates/*.yaml
releaseNotes:
  queryTemplates:
    fixed: |
      project = AI AND ((fixVersion = AI-v2.6.0 AND status NOT IN (Backlog,Blocked, Cancelled, 已取消, 已拒绝) AND (assignee NOT IN membersOf(test) OR assignee IS EMPTY) AND (issuetype IN (Epic, Improvement, Document) OR (issuetype IN (Bug, Improvement) AND (issueFunction in linkedIssuesOf("affectedVersion in versionMatch('AI-v1.[0-5].[0-9]|AI-v2.[0-9].[0-9]')", clones) OR issueFunction in linkedIssuesOf("affectedVersion in versionMatch('AI-v1.[0-5].[0-9]|AI-v2.[0-9].[0-9]')", "is cloned by") OR affectedVersion in versionMatch("AI-v1.[0-5].[0-9]|AI-v2.[0-1].[0-9]"))))) OR ACPFixVersions = AI-v2.6.0) AND issuetype = Bug AND ReleaseNotesStatus = Publish ORDER BY issuetype ASC
    unfixed: |
      type = Bug AND project = AI AND affectedVersion = AI-v2.6.0 AND status NOT IN (Resolved, Closed, Done) AND labels not in (安全问题) AND ((issueFunction in linkedIssuesOf("affectedVersion in versionMatch('AI-v1.[0-5].[0-9]|AI-v2.[0-9].[0-9]')", clones) OR issueFunction in linkedIssuesOf("affectedVersion in versionMatch('AI-v1.[0-5].[0-9]|AI-v2.[0-9].[0-9]')", "is cloned by") OR affectedVersion in versionMatch("AI-v1.[0-5].[0-9]|AI-v2.[0-9].[0-9]")) OR ACPFixVersions = AI-v2.6.0) AND (resolution IS EMPTY OR resolution IN ("Won't Do")) AND ReleaseNotesStatus = Publish
