apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: hello-mpi
spec:
  runtimeRef:
    apiGroup: trainer.kubeflow.org
    kind: TrainingRuntime
    name: openmpi-trainingruntime
  trainer:
    numNodes: 2
    numProcPerNode: 1
    image: mpioperator/mpi-pi:v0.6.0-openmpi
    command:
      - mpirun
      - /home/mpiuser/pi
    resourcesPerNode:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi
