apiVersion: v1
items:
- apiVersion: auth.alauda.io/v1beta1
  kind: FunctionResource
  metadata:
    annotations:
      auth.cpaas.io/functionresource.function.id: "3"
      auth.cpaas.io/functionresource.module.id: "200"
      cpaas.io/functionresource.function.display-name: 推理服务
      cpaas.io/functionresource.function.display-name.en: profiles
      cpaas.io/functionresource.module.display-name: Machine Learning
      cpaas.io/functionresource.module.display-name.en: Machine Learning
      helm.sh/chart-version: v1.3.1-rc.21.ga91c2d48
      helm.sh/original-name: aml-profiles
    creationTimestamp: "2025-03-10T13:39:55Z"
    generation: 1
    labels:
      auth.cpaas.io/functionresource.function: profiles
      auth.cpaas.io/functionresource.module: aml
      auth.cpaas.io/product: console-aml
      helm.sh/chart-name: aml-global
      helm.sh/release-name: aml-global
      helm.sh/release-namespace: cpaas-system
    name: aml-profiles
    resourceVersion: "10183553"
    uid: 7070887e-b24c-4569-b974-3bca59e1b407
  spec:
    rules:
    - apiGroup: kubeflow.org
      bindCluster: business
      bindNamespacePart: ""
      bindScope: cluster
      resources:
      - profiles
- apiVersion: auth.alauda.io/v1beta1
  kind: FunctionResource
  metadata:
    annotations:
      auth.cpaas.io/functionresource.function.id: "1"
      auth.cpaas.io/functionresource.module.id: "200"
      cpaas.io/functionresource.function.display-name: 推理运行时
      cpaas.io/functionresource.function.display-name.en: Cluster Serving Runtimes
      cpaas.io/functionresource.module.display-name: Machine Learning
      cpaas.io/functionresource.module.display-name.en: Machine Learning
      helm.sh/chart-version: v1.3.1-rc.21.ga91c2d48
      helm.sh/original-name: aml-clusterservingruntimes
    creationTimestamp: "2025-03-10T13:39:55Z"
    generation: 1
    labels:
      auth.cpaas.io/functionresource.function: clusterservingruntimes
      auth.cpaas.io/functionresource.module: aml
      auth.cpaas.io/product: console-aml
      helm.sh/chart-name: aml-global
      helm.sh/release-name: aml-global
      helm.sh/release-namespace: cpaas-system
    name: aml-clusterservingruntimes
    resourceVersion: "10183551"
    uid: 9404bcb2-db40-41ea-be91-9ff777b0a3ff
  spec:
    rules:
    - apiGroup: serving.kserve.io
      bindCluster: business
      bindNamespacePart: ""
      bindScope: cluster
      resources:
      - clusterservingruntimes
kind: List
metadata:
  resourceVersion: ""