#!/usr/bin/env bash
# Generate a KFP v2 IR (pipeline_spec + kubernetes platform_spec) for a single
# CONTAINER component that logs to MLflow. A container component is used on
# purpose: it runs the given image+command directly, with NO `pip install kfp`
# bootstrap — so it works on clusters where PyPI is blocked, as long as the
# image already contains mlflow (the mlops/mlflow-acp image does).
#
# The step script is base64-embedded so the IR is self-contained (no ConfigMap).
# The workspace ServiceAccount token is injected as MLFLOW_TRACKING_TOKEN via the
# kubernetes platform spec (secretAsEnv) — the same mechanism kfp-kubernetes'
# use_secret_as_env emits. The KFP run id reaches the step as KFP_RUN_ID via
# fieldPathAsEnv from the workflow pod label `pipeline/runid` (the
# {{$.pipeline_job_uuid}} placeholder is NOT substituted for raw container
# components, so the Downward-API label is the reliable source).
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
IMAGE="${STEP_IMAGE:-152-231-registry.alauda.cn:60070/mlops/mlflow-acp:v3.10.0.20260522101604}"
TRACKING_URI="${MLFLOW_TRACKING_URI:-http://mlflow-e2e-direct.kubeflow:5000}"
WORKSPACE="${MLFLOW_WORKSPACE:-mlflow-e2e}"
EXPERIMENT="${MLFLOW_EXPERIMENT_NAME:-aip-mlflow-pipeline-8.1.2}"
SECRET_NAME="${MLFLOW_TOKEN_SECRET:-mlflow-pipeline-token}"
OUT="${1:-$HERE/mlflow-pipeline.yaml}"

B64="$(base64 -w0 "$HERE/mlflow_pipeline_step.py")"

cat > "$OUT" <<YAML
# KFP v2 IR — single container component that opens an MLflow run from the
# pipeline-run context and logs params + a metric + a tiny artifact, tagging the
# run with the KFP pipeline run id ({{\$.pipeline_job_uuid}}). Generated by
# build-pipeline-ir.sh; the step source is e2e/assets/mlflow_pipeline_step.py.
components:
  comp-log-to-mlflow:
    executorLabel: exec-log-to-mlflow
deploymentSpec:
  executors:
    exec-log-to-mlflow:
      container:
        image: ${IMAGE}
        command:
        - sh
        - -ec
        - |
          printf '%s' "\$0" | base64 -d > /tmp/step.py
          exec python /tmp/step.py --workspace="\$1" --experiment="\$2" --tracking-uri="\$3"
        args:
        - ${B64}
        - ${WORKSPACE}
        - ${EXPERIMENT}
        - ${TRACKING_URI}
pipelineInfo:
  name: aip-mlflow-integration
  description: AIP-to-MLflow backend integration smoke (8.1.2).
root:
  dag:
    tasks:
      log-to-mlflow:
        cachingOptions:
          enableCache: false
        componentRef:
          name: comp-log-to-mlflow
        taskInfo:
          name: log-to-mlflow
schemaVersion: 2.1.0
sdkVersion: kfp-2.16.0
---
platforms:
  kubernetes:
    deploymentSpec:
      executors:
        exec-log-to-mlflow:
          secretAsEnv:
          - secretName: ${SECRET_NAME}
            keyToEnv:
            - secretKey: token
              envVar: MLFLOW_TRACKING_TOKEN
          fieldPathAsEnv:
          - name: KFP_RUN_ID
            fieldPath: "metadata.labels['pipeline/runid']"
YAML
echo "wrote $OUT"
