apiVersion: v1
items:
- apiVersion: auth.alauda.io/v1beta1
  kind: RoleTemplate
  metadata:
    annotations:
      auth.cpaas.io/role.id: "8"
      cpaas.io/creator: system
      cpaas.io/description: 负责命名空间配置管理
      cpaas.io/description.en: Responsible for managing config in namespace level.
      cpaas.io/display-name: AML 命名空间 Owner
      cpaas.io/display-name.en: AML Namespace Owner
      helm.sh/chart-version: v1.3.1-rc.21.ga91c2d48
      helm.sh/original-name: aml-namespace-owner
    creationTimestamp: "2025-03-10T13:39:55Z"
    generation: 1
    labels:
      auth.cpaas.io/creator.email: ""
      auth.cpaas.io/roletemplate.level: namespace
      auth.cpaas.io/roletemplate.official: "false"
      helm.sh/chart-name: aml-global
      helm.sh/release-name: aml-global
      helm.sh/release-namespace: cpaas-system
    name: aml-namespace-owner
    resourceVersion: "10183557"
    uid: 905f770e-8616-4438-b82f-d366e2bad12e
  spec:
    customRules:
    - apiGroup: kubeflow.org
      resources:
      - poddefaults
      verbs:
      - get
      - list
      - watch
    - apiGroup: serving.knative.dev
      resources:
      - '*'
      verbs:
      - '*'
    - apiGroup: kubeflow.org
      resources:
      - notebooks
      - notebooks/finalizers
      - poddefaults
      verbs:
      - get
      - list
      - create
      - delete
    - apiGroup: serving.knative.dev
      resources:
      - '*'
      verbs:
      - create
      - update
      - patch
      - delete
    - apiGroup: istio.io
      resources:
      - '*'
      verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
    - apiGroup: networking.istio.io
      resources:
      - '*'
      verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
    - apiGroup: kubeflow.org
      resources:
      - experiments
      - trials
      - suggestions
      verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
    - apiGroup: serving.kserve.io
      resources:
      - inferenceservices
      - trainedmodels
      - servingruntimes
      verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
    - apiGroup: serving.knative.dev
      resources:
      - services
      - services/status
      - routes
      - routes/status
      - configurations
      - configurations/status
      - revisions
      - revisions/status
      verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
    - apiGroup: '*'
      resources:
      - pods/attach
      - pods/exec
      - pods/portforward
      - pods/proxy
      - secrets
      - services/proxy
      verbs:
      - get
      - list
      - watch
    - apiGroup: '*'
      resources:
      - nodes
      verbs:
      - get
      - list
      - watch
    - apiGroup: '*'
      resources:
      - serviceaccounts
      verbs:
      - impersonate
    - apiGroup: '*'
      resources:
      - pods
      - pods/attach
      - pods/exec
      - pods/portforward
      - pods/proxy
      verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    - apiGroup: '*'
      resources:
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - replicationcontrollers
      - replicationcontrollers/scale
      - secrets
      - serviceaccounts
      - services
      - services/proxy
      verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    - apiGroup: apps
      resources:
      - daemonsets
      - deployments
      - deployments/rollback
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
      - statefulsets/scale
      verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    - apiGroup: autoscaling
      resources:
      - horizontalpodautoscalers
      verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    - apiGroup: batch
      resources:
      - cronjobs
      - jobs
      verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    - apiGroup: extensions
      resources:
      - daemonsets
      - deployments
      - deployments/rollback
      - deployments/scale
      - ingresses
      - networkpolicies
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
      verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    - apiGroup: policy
      resources:
      - poddisruptionbudgets
      verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    - apiGroup: networking.k8s.io
      resources:
      - ingresses
      - networkpolicies
      verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    - apiGroup: scheduling.volcano.sh
      resources:
      - podgroups
      verbs:
      - list
      - get
      - create
      - delete
      - patch
      - update
    - apiGroup: batch.volcano.sh
      resources:
      - jobs
      verbs:
      - list
      - get
      - create
      - delete
      - patch
      - update
    - apiGroup: pipelines.kubeflow.org
      resources:
      - pipelines
      - pipelines/versions
      verbs:
      - create
      - delete
      - update
    - apiGroup: pipelines.kubeflow.org
      resources:
      - experiments
      verbs:
      - archive
      - create
      - delete
      - unarchive
    - apiGroup: pipelines.kubeflow.org
      resources:
      - runs
      verbs:
      - archive
      - create
      - delete
      - retry
      - terminate
      - unarchive
      - reportMetrics
      - readArtifact
    - apiGroup: pipelines.kubeflow.org
      resources:
      - jobs
      verbs:
      - create
      - delete
      - disable
      - enable
    - apiGroup: kubeflow.org
      resources:
      - scheduledworkflows
      verbs:
      - '*'
    - apiGroup: argoproj.io
      resources:
      - cronworkflows
      - cronworkflows/finalizers
      - workflows
      - workflows/finalizers
      - workfloweventbindings
      - workflowtemplates
      verbs:
      - '*'
    - apiGroup: pipelines.kubeflow.org
      resources:
      - pipelines
      - pipelines/versions
      - experiments
      - jobs
      verbs:
      - get
      - list
    - apiGroup: pipelines.kubeflow.org
      resources:
      - runs
      verbs:
      - get
      - list
      - readArtifact
    - apiGroup: kubeflow.org
      resources:
      - viewers
      verbs:
      - create
      - get
      - delete
    - apiGroup: pipelines.kubeflow.org
      resources:
      - visualizations
      verbs:
      - create
    - apiGroup: kubeflow.org
      resources:
      - mpijobs
      - tfjobs
      - pytorchjobs
      - mxjobs
      - xgboostjobs
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroup: kubeflow.org
      resources:
      - mpijobs/status
      - tfjobs/status
      - pytorchjobs/status
      - mxjobs/status
      - xgboostjobs/status
      verbs:
      - get
    - apiGroup: kubeflow.org
      resources:
      - notebooks
      - notebooks/finalizers
      - poddefaults
      verbs:
      - get
      - list
    - apiGroup: storage.k8s.io
      resources:
      - storageclasses
      verbs:
      - get
      - list
      - watch
    - apiGroup: serving.knative.dev
      resources:
      - '*'
      verbs:
      - get
      - list
      - watch
    - apiGroup: networking.internal.knative.dev
      resources:
      - '*'
      verbs:
      - get
      - list
      - watch
    - apiGroup: autoscaling.internal.knative.dev
      resources:
      - '*'
      verbs:
      - get
      - list
      - watch
    - apiGroup: caching.internal.knative.dev
      resources:
      - '*'
      verbs:
      - get
      - list
      - watch
    - apiGroup: kubeflow.org
      resources:
      - experiments
      - trials
      - suggestions
      verbs:
      - get
      - list
      - watch
    - apiGroup: serving.kserve.io
      resources:
      - inferenceservices
      - trainedmodels
      - servingruntimes
      verbs:
      - get
      - list
      - watch
    - apiGroup: serving.knative.dev
      resources:
      - services
      - services/status
      - routes
      - routes/status
      - configurations
      - configurations/status
      - revisions
      - revisions/status
      verbs:
      - get
      - list
    - apiGroup: '*'
      resources:
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - persistentvolumeclaims/status
      - pods
      - replicationcontrollers
      - replicationcontrollers/scale
      - serviceaccounts
      - services
      - services/status
      verbs:
      - get
      - list
      - watch
    - apiGroup: '*'
      resources:
      - bindings
      - events
      - limitranges
      - namespaces/status
      - pods/log
      - pods/status
      - replicationcontrollers/status
      - resourcequotas
      - resourcequotas/status
      verbs:
      - get
      - list
      - watch
    - apiGroup: '*'
      resources:
      - namespaces
      verbs:
      - get
      - list
      - watch
    - apiGroup: apps
      resources:
      - controllerrevisions
      - daemonsets
      - daemonsets/status
      - deployments
      - deployments/scale
      - deployments/status
      - replicasets
      - replicasets/scale
      - replicasets/status
      - statefulsets
      - statefulsets/scale
      - statefulsets/status
      verbs:
      - get
      - list
      - watch
    - apiGroup: autoscaling
      resources:
      - horizontalpodautoscalers
      - horizontalpodautoscalers/status
      verbs:
      - get
      - list
      - watch
    - apiGroup: batch
      resources:
      - cronjobs
      - cronjobs/status
      - jobs
      - jobs/status
      verbs:
      - get
      - list
      - watch
    - apiGroup: extensions
      resources:
      - daemonsets
      - daemonsets/status
      - deployments
      - deployments/scale
      - deployments/status
      - ingresses
      - ingresses/status
      - networkpolicies
      - replicasets
      - replicasets/scale
      - replicasets/status
      - replicationcontrollers/scale
      verbs:
      - get
      - list
      - watch
    - apiGroup: policy
      resources:
      - poddisruptionbudgets
      - poddisruptionbudgets/status
      verbs:
      - get
      - list
      - watch
    - apiGroup: networking.k8s.io
      resources:
      - ingresses
      - ingresses/status
      - networkpolicies
      verbs:
      - get
      - list
      - watch
    - apiGroup: kubeflow.org
      resources:
      - mpijobs
      - tfjobs
      - pytorchjobs
      - mxjobs
      - xgboostjobs
      verbs:
      - get
      - list
      - watch
    - apiGroup: kubeflow.org
      resources:
      - notebooks
      - notebooks/status
      verbs:
      - get
      - list
      - watch
    - apiGroup: tensorboard.kubeflow.org
      resources:
      - tensorboards
      - tensorboards/finalizers
      verbs:
      - get
      - list
    - apiGroup: kubeflow.org
      resources:
      - notebooks
      - notebooks/status
      verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
    - apiGroup: tensorboard.kubeflow.org
      resources:
      - tensorboards
      - tensorboards/finalizers
      verbs:
      - get
      - list
      - create
      - delete
    - apiGroup: '*'
      resources:
      - persistentvolumeclaims
      verbs:
      - create
      - delete
      - get
      - list
      - watch
      - update
      - patch
    - apiGroup: authorization.k8s.io
      resources:
      - localsubjectaccessreviews
      verbs:
      - create
    - apiGroup: rbac.authorization.k8s.io
      resources:
      - rolebindings
      - roles
      verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    rules:
    - functionResourceRef: aml-clusterservingruntimes
      verbs:
      - get
      - list
      - watch
    - functionResourceRef: aml-profiles
      verbs:
      - get
      - list
      - watch
      - patch
      - update
kind: List
metadata:
  resourceVersion: ""